baseurl = "https://id-arquitectos.github.io/"
languageCode = "es-mx"
title = "id&arq arquitectura creativa"
theme = "hugo-creative-theme"

[params]
  name = "id&arq"
  description = "Arquitectura Creativa"
  favicon = "favicon.ico"

  [params.navigation]
    brand = "id&arq"
    color = "#765B56"

    [params.navigation.links]
      about = "Acerca de"
      services = "Servicios"
      portfolio = "Conócenos"
      location = "Mapa"
      contact = "Contacto"

  [params.hero]
    slogan = "*Arquitectura* Creativa"
    #buttonText = "Conoce más"
    #subtitle= "Firma de arquitectos empresa con la más alta calidad."

  [params.about]
    headline    = "Somos una firma de arquitectos especializada en diseño de espacios corporativos, construcción y administración."
    #description = "Firma de arquitectos empresa con la más alta calidad."

  [params.services]
    headline = "A tu servicio"
    description = "Nuestro compromiso es construir y diseñar espacios acorde de los estándares de su empresa con la más alta calidad."

    [[params.services.list]]
      icon = "fa-black-tie"
      title = "Corportativa"
      description = "Creación de espacios de trabajo."

    [[params.services.list]]
      icon = "fa-cart-plus"
      title = "Retail"
      description = "Soluciones para el ramo comercial."

    [[params.services.list]]
      icon = "fa-home"
      title = "Residencial"
      description = "Espacios de vivienda."

  [params.portfolio.modal]
    client = "Cliente"
    date = "Fecha"
    category = "Categoría"
    buttonText = "Cerrar"

  [params.contact]
    #headline = "Contáctanos"
    #description = "Queremos darte el mejor servicio"
    street = "Tintoreto 92 - 301, Col. Cd. de los Deportes 03710 Ciudad de México"

    [[params.contact.list]]
      name = "Ricardo Franco Arredondo"
      position = "Gerente de Nuevos Negocios"
      email = "ricfranco@idearquitectos.com.mx"
      phone = "01 (55) 6729 9790"
      phone_clean = "015567299790"

    [[params.contact.list]]
      name = "Raúl Franco Arredondo"
      position = "Director General"
      email = "rfranco@idearquitectos.com.mx"
      phone = "01 (55) 6729 9790"
      phone_clean = "015567299790"

  [params.location]
    latitude = "19.383505"
    longitude = "-99.1824065"
    zoom = 17
    maps_api_key = "AIzaSyARMu6bLLVyhbPpiO2YSKL3OAhhx_QQ2uU"
