baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "creative"
[params]
  	name = "Nombre"
	description = "Descripción"
	favicon = "favicon.ico"